bieniu/ha-shellies-discovery-gen2

- python_scripts/shellies_discovery_gen2.py
> Add firmware version checking

- python_scripts/shellies_discovery_gen2.py
> Fix consumption types error

- python_scripts/shellies_discovery_gen2.py
> Fix set positon template

- python_scripts/shellies_discovery_gen2.py
Related to: https://github.com/bieniu/ha-shellies-discovery-gen2/issues/56
> Improve min firmware check

- README.md
- info.md
- python_scripts/shellies_discovery_gen2.py
> Auto install/update device script

- python_scripts/shellies_discovery_gen2.py
> Add fan platform for relays

- README.md
- info.md
- python_scripts/shellies_discovery_gen2.py
> Add `script_prefix` argument

- python_scripts/shellies_discovery_gen2.py
> Fix topic for the device script installation

- python_scripts/shellies_discovery_gen2.py
Ralated to https://github.com/bieniu/ha-shellies-discovery-gen2/issues/157
> Use `script_prefix` to generate `source_topic`

- hacs.json
- python_scripts/shellies_discovery_gen2.py
> Migrate rounding values to `suggested_display_precision`

- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/167
> Remove value checking from templates

- python_scripts/shellies_discovery_gen2.py
Addition of external voltmeter enabled by the Shelly Plus Addon
> Addition of external voltmeter to sensors

- python_scripts/shellies_discovery_gen2.py
> Fix event template

- .github/workflows/release-drafter.yml
- hacs.json
- python_scripts/shellies_discovery_gen2.py
Related to: https://github.com/home-assistant/core/pull/98782
> Add support for origin info

- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/333
> Add support for Pro 3EM Add-on

- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/339
> Hardcode wakeup_period

- python_scripts/shellies_discovery_gen2.py
Close https://github.com/bieniu/ha-shellies-discovery-gen2/issues/370
> Add support for external/input sensors for Shelly Plus Uni

- hacs.json
- python_scripts/shellies_discovery_gen2.py
Home Assistant 2004.9+ required
> Support `DeviceInfo.model_id`

- README.md
- info.md
- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/489
> Add support for Plug S Gen3

- python_scripts/shellies_discovery_gen2.py
Relates to https://github.com/bieniu/ha-shellies-discovery-gen2/issues/498
> Raise an exception if no MQTT component in the data

- python_scripts/shellies_discovery_gen2.py
Related to https://github.com/bieniu/ha-shellies-discovery-gen2/issues/504
> Log warning when BLU device is unknown or not supported

- README.md
- info.md
Related to https://github.com/bieniu/ha-shellies-discovery-gen2/issues/498
> Include only config for GetComponents

- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/561
> Avoid single quote char in names

- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/563
> Avoid single quote char in names - once again

- python_scripts/shellies_discovery_gen2.py
Fixes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/584
> Move `transition` to `params` for `Light.Set` service

- README.md
- info.md
- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/604
> Add support for LinkedGo Smart Thermostat ST802-B

- python_scripts/shellies_discovery_gen2.py
Fixes https://github.com/bieniu/ha-shellies-discovery-gen2
> Fix `model_id` lookup for BLU devices

- python_scripts/shellies_discovery_gen2.py
Closes https://github.com/bieniu/ha-shellies-discovery-gen2/issues/656
> Use both methods to set `MODEL_ID` for BLU devices
